Repository Computerization/computerization.github.io, pull requests merged in 2020-04, with the labels that each got.

#74 RFC: Timeline-based Alumni Page
  docusaurus.config.js
  docusaurus.d.ts
  package.json
  src/components/AlumniTimeline.module.css
  src/components/AlumniTimeline.tsx
  src/components/Members.module.css
  src/components/Members.tsx
  src/pages/alumni.module.css
  src/pages/alumni.tsx
  src/pages/index.js
  yarn.lock
Labels: enhancement

#80 Alumni Directory: Add Jiameng Du
  src/pages/alumni.tsx
  static/img/alumni/Jiameng_Du.png
Labels: alumni

#82 Switch logo SVG to vector graphic
  static/img/logo.svg
Labels: bug, enhancement

#84 Create document for enspire
  docs/enspire/what-is-enspire.md
  sidebars.js
Labels: documentation

#85 Make README Files clearer
  README.md
  static/README.md
Labels: documentation

#86 New design for alumni page: multiple links & short bio
  src/components/AlumniTimeline.module.css
  src/components/MemberCard.module.css
  src/components/MemberCard.tsx
  src/components/Members.module.css
  src/components/Members.tsx
  src/pages/alumni.tsx
Labels: alumni, enhancement

#87 Update Alumni Directory
  README.md
  src/components/MemberCard.module.css
  src/components/MemberCard.tsx
  src/pages/alumni.tsx
  static/img/alumni/Default.svg
  static/img/alumni/Eric_Zhang.jpg
  static/img/alumni/Guohao_Ang.jpg
  static/img/alumni/Jiameng_Du.jpg
  static/img/alumni/Jiameng_Du.png
  static/img/alumni/Jichu_Yang.jpg
  static/img/alumni/Jimmy_Gan.jpg
  static/img/alumni/Qinzi_Zhang.jpg
  static/img/alumni/Rachel_Gu.png
  static/img/alumni/Tim_Zhu.jpg
  static/img/alumni/Yuchen_Zhong.jpg
  static/img/alumni/Yudi_Yang.jpg
Labels: alumni
